[tool.poetry]
name = "llm-eval-test"
version = "0.1.0"
description = ""
authors = ["Samuel Monson <smonson@redhat.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
lm-eval = { extras = ["api"], git = "https://github.com/EleutherAI/lm-evaluation-harness", rev = "57272b6" }
unitxt = "1.14.0"
# Use CPU torch to cut down on deps
torch = {version = ">=1.8", source = "torch-cpu"}


[tool.poetry.scripts]
llm-eval-test = "llm_eval_test.__main__:eval_cli"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"


[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
